In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

In [3]:
tf.constant((-1, 3))

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1,  3])>

In [4]:
print(tf.__version__)

2.1.0


In [5]:
x = tf.constant(range(12))

print(x.shape)

(12,)


In [6]:
tf.placeholder??

Object `tf.placeholder` not found.


In [9]:
tf.zeros((2,3),dtype='float32')

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [10]:
tf.train.GradientDescentOptimizer

AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'GradientDescentOptimizer'

In [13]:
import numpy as np

In [21]:
y = [0.9,0.9,0,0,0.1]
y_ = [0,0.1,0.1,0,0.9]
tf.reduce_mean(-tf.reduce_sum(y_ * tf.math.log(y)))

<tf.Tensor: shape=(), dtype=float32, numpy=nan>

In [22]:
y_ * tf.math.log(y)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-0.        , -0.01053606,        -inf,         nan, -2.0723267 ],
      dtype=float32)>

In [23]:
-tf.reduce_sum(y_ * tf.math.log(y))

<tf.Tensor: shape=(), dtype=float32, numpy=nan>

In [24]:
a = tf.constant([0.9,0.9,0,0,0.1])
a

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0.9, 0.9, 0. , 0. , 0.1], dtype=float32)>

In [25]:
a.numpy()

array([0.9, 0.9, 0. , 0. , 0.1], dtype=float32)

In [26]:
tf.argmax??

In [31]:
tf.argmax(y, 0)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [32]:
tf.argmax(y_, 0)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [35]:
y = [0.9,0.9,0,0,0.1]
y_ = [0,0.1,0.1,0,0.9]
c = tf.equal(tf.argmax(y, 0), tf.argmax(y_, 0))

tf.cast(c, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
def lr(self):
    w = tf.Variable(tf.random.normal(self.seq_length, self.config.num_classes))
    b = tf.Variable(tf.random.normal([self.config.num_classes]))
    self.y_ = tf.matmul(self.X, w) + b
    cross_entropy = tf.reduce_mean(-tf.reduce_sum(self.y_ * tf.math.log(self.y)))

    def sgd(params, lr, batch_size, grads):
        for i,param in enumerate(params):
            param.assign_sub(lr * grads[i]/batch_size)

    with tf.GradientTape() as t:
        t.watch([w,b])
    grads = t.gradient(cross_entropy, [w,b])
    sgd([w,b], 0.5, self.batch_size, grads)
    

In [36]:
class LrModel(object):
    def __init__(self, config, seq_length, X,y, batch_size):
        self.config = config
        self.seq_length = seq_length
        self.X = X
        self.y = y
        self.batch_size = batch_size
        self.lr()
 
    def lr(self):
        w = tf.Variable(tf.random.normal(self.seq_length, self.config.num_classes))
        b = tf.Variable(tf.random.normal([self.config.num_classes]))
        self.y_ = tf.matmul(self.X, w) + b
        cross_entropy = tf.reduce_mean(-tf.reduce_sum(self.y_ * tf.math.log(self.y)))
        self.loss = tf.reduce_mean(cross_entropy)

        def sgd(params, lr, batch_size, grads):
            for i,param in enumerate(params):
                param.assign_sub(lr * grads[i]/batch_size)
        
        with tf.GradientTape() as t:
            t.watch([w,b])
        grads = t.gradient(cross_entropy, [w,b])
        sgd([w,b], 0.5, self.batch_size, grads)

        correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(self.y_, 1))
        self.accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


In [37]:
config, seq_length, batch_xs, batch_ys = 
model = LrModel(config, seq_length, batch_xs, batch_ys)

NameError: name 'config' is not defined

In [38]:
tf.nn.softmax??

In [40]:
tf.random.normal((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.13790156, -2.0732358 , -0.04170846],
       [-1.7901222 , -0.9143984 , -0.10762674]], dtype=float32)>

In [41]:
tf.random.normal([3])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.49478203, -0.4748924 ,  0.40968284], dtype=float32)>

In [46]:
import time
a = time.time()
for i in range(1000000):
    ans = 0 + i
b = time.time() - a
print(b)

0.09754586219787598


In [48]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [195]:
a = np.array([[1,2,3]])
a = tf.Variable(a,dtype=tf.float32)
b = tf.constant([[4,5,6,7,8,9,1,1,1]],dtype=tf.float32)
b = tf.reshape(b,shape=(3,-1))
# a = tf.constant(a)
tf.matmul(a, b)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[21., 24., 27.]], dtype=float32)>

In [149]:
a.shape

(1, 3)

In [150]:
b.shape

TensorShape([3, 3])

In [187]:
c = tf.matmul(a, b)
c = tf.reshape(c,shape=(1,-1))
c

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[21, 24, 27]])>

In [168]:
c.shape

TensorShape([1, 3])

In [159]:
c = tf.squeeze(c, axis=0)
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 24, 27])>

In [162]:
type(c.numpy())

numpy.ndarray

In [155]:
tf.nn.softmax(c)

NotFoundError: Could not find valid device for node.
Node:{{node Softmax}}
All kernels registered for op Softmax :
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
 [Op:Softmax]

In [169]:
X.shape

TensorShape([2, 5])

In [176]:
d = tf.constant([[1,2,3,4,5],
                [6,7,8,9,10]],dtype='float32')
tf.nn.softmax(d)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.01165623, 0.03168492, 0.08612854, 0.23412165, 0.6364086 ],
       [0.01165623, 0.03168492, 0.08612854, 0.23412165, 0.6364086 ]],
      dtype=float32)>

In [172]:
X = tf.random.normal(shape=(2, 5))
tf.nn.softmax(X)

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.39877483, 0.263803  , 0.15187943, 0.06549548, 0.12004722],
       [0.29959592, 0.399364  , 0.05530592, 0.05936319, 0.18637098]],
      dtype=float32)>

In [113]:
type(a)

numpy.ndarray

In [114]:
a.shape

(1, 3)

In [115]:
b.shape

TensorShape([3, 2])

In [94]:
a = tf.expand_dims(a,axis=0)
b = tf.expand_dims(b,axis=1)
tf.matmul(a, b)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[32]])>

In [95]:
a.shape

TensorShape([1, 3])

In [96]:
b.shape

TensorShape([3, 1])

In [60]:
a = np.array([1,2,3])
a = a.reshape((1,3))
a

array([[1, 2, 3]])

In [62]:
b.shape

TensorShape([3, 3])

### 增加维度

In [81]:
b = tf.expand_dims(b,axis=1)
b

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[4],
       [5],
       [6]])>

In [82]:
b.shape

TensorShape([3, 1])

### 删除维度

In [80]:
b = tf.squeeze(b, axis=1)
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [198]:
y = [[0,0,1,0,0,0,0,0,0,0]]
tf.argmax(y, 1)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([2], dtype=int64)>